version: '3'

services:
  tinkoff-invest-robot-sandbox-2026-1:
    image: 'romanew/invest:sandbox-2026-1-latest'
    container_name: tinkoff-invest-robot-sandbox-2026-1
    network_mode: host
    environment:
      - server.port=10003
      - spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/invest-sandbox-2026-1
      - spring.datasource.username=${POSTGRES_USER}
      - spring.datasource.password=${POSTGRES_PASSWORD}
      - candle.listener.enabled=true
      - tinkoff.emulator=false
      - tinkoff.is-token-sandbox=true
      - tinkoff.token=${TINKOFF_TOKEN_SANDBOX}
      - tinkoff.account-id=d83b1023-8703-4c0c-9be2-7d5323335826
#      - telegram.bot.token=${TELEGRAM_BOT_TOKEN}
#      - telegram.bot.chat-id=${TELEGRAM_BOT_CHAT_ID}
    restart: always
    deploy:
      resources:
        limits:
          memory: 768M